//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delta_Dent.WebService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("JetBrains.SvcUtil", "777.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Delta_Dent.WebService.WebServiceSoap")]
    public interface WebServiceSoap
    {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Delta_Dent.WebService.HelloWorldResponse HelloWorld(Delta_Dent.WebService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Delta_Dent.WebService.HelloWorldResponse> HelloWorldAsync(Delta_Dent.WebService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (Sum_x0020_of_x0020_numbers) of message Sum_x0020_of_x0020_numbers does not match the default value (Sum)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sum of numbers", ReplyAction="*")]
        Delta_Dent.WebService.Sumofnumbers1 Sum(Delta_Dent.WebService.Sumofnumbers request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sum of numbers", ReplyAction="*")]
        System.Threading.Tasks.Task<Delta_Dent.WebService.Sumofnumbers1> SumAsync(Delta_Dent.WebService.Sumofnumbers request);
        
        // CODEGEN: Generating message contract since element name firstName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SavePatient", ReplyAction="*")]
        Delta_Dent.WebService.SavePatientResponse SavePatient(Delta_Dent.WebService.SavePatientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SavePatient", ReplyAction="*")]
        System.Threading.Tasks.Task<Delta_Dent.WebService.SavePatientResponse> SavePatientAsync(Delta_Dent.WebService.SavePatientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SavePatientTest", ReplyAction="*")]
        void SavePatientTest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SavePatientTest", ReplyAction="*")]
        System.Threading.Tasks.Task SavePatientTestAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("JetBrains.SvcUtil", "777.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Delta_Dent.WebService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest()
        {
        }
        
        public HelloWorldRequest(Delta_Dent.WebService.HelloWorldRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("JetBrains.SvcUtil", "777.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody
    {
        
        public HelloWorldRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("JetBrains.SvcUtil", "777.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Delta_Dent.WebService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse()
        {
        }
        
        public HelloWorldResponse(Delta_Dent.WebService.HelloWorldResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("JetBrains.SvcUtil", "777.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody()
        {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult)
        {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("JetBrains.SvcUtil", "777.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Sum of numbers", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Sumofnumbers
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int x;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int y;
        
        public Sumofnumbers()
        {
        }
        
        public Sumofnumbers(int x, int y)
        {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("JetBrains.SvcUtil", "777.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Sum of numbersResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Sumofnumbers1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Sum_x0020_of_x0020_numbersResult", Namespace="http://tempuri.org/", Order=0)]
        public int SumofnumbersResult;
        
        public Sumofnumbers1()
        {
        }
        
        public Sumofnumbers1(int SumofnumbersResult)
        {
            this.SumofnumbersResult = SumofnumbersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("JetBrains.SvcUtil", "777.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SavePatientRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SavePatient", Namespace="http://tempuri.org/", Order=0)]
        public Delta_Dent.WebService.SavePatientRequestBody Body;
        
        public SavePatientRequest()
        {
        }
        
        public SavePatientRequest(Delta_Dent.WebService.SavePatientRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("JetBrains.SvcUtil", "777.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SavePatientRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string surname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string genderString;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string telephone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string cf;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string cAsl;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.DateTime birthDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string birthPlace;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string birthProvince;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public bool foreigner;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string billable;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public bool completed;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public bool documented;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public int doctorId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public bool locked;
        
        public SavePatientRequestBody()
        {
        }
        
        public SavePatientRequestBody(string firstName, string surname, string genderString, string telephone, string cf, string cAsl, System.DateTime birthDate, string birthPlace, string birthProvince, bool foreigner, string billable, bool completed, bool documented, int doctorId, bool locked)
        {
            this.firstName = firstName;
            this.surname = surname;
            this.genderString = genderString;
            this.telephone = telephone;
            this.cf = cf;
            this.cAsl = cAsl;
            this.birthDate = birthDate;
            this.birthPlace = birthPlace;
            this.birthProvince = birthProvince;
            this.foreigner = foreigner;
            this.billable = billable;
            this.completed = completed;
            this.documented = documented;
            this.doctorId = doctorId;
            this.locked = locked;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("JetBrains.SvcUtil", "777.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SavePatientResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SavePatientResponse", Namespace="http://tempuri.org/", Order=0)]
        public Delta_Dent.WebService.SavePatientResponseBody Body;
        
        public SavePatientResponse()
        {
        }
        
        public SavePatientResponse(Delta_Dent.WebService.SavePatientResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("JetBrains.SvcUtil", "777.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SavePatientResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SavePatientResult;
        
        public SavePatientResponseBody()
        {
        }
        
        public SavePatientResponseBody(int SavePatientResult)
        {
            this.SavePatientResult = SavePatientResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("JetBrains.SvcUtil", "777.0.0.0")]
    public interface WebServiceSoapChannel : Delta_Dent.WebService.WebServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("JetBrains.SvcUtil", "777.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Delta_Dent.WebService.WebServiceSoap>, Delta_Dent.WebService.WebServiceSoap
    {
        
        public WebServiceSoapClient()
        {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Delta_Dent.WebService.HelloWorldResponse Delta_Dent.WebService.WebServiceSoap.HelloWorld(Delta_Dent.WebService.HelloWorldRequest request)
        {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld()
        {
            Delta_Dent.WebService.HelloWorldRequest inValue = new Delta_Dent.WebService.HelloWorldRequest();
            inValue.Body = new Delta_Dent.WebService.HelloWorldRequestBody();
            Delta_Dent.WebService.HelloWorldResponse retVal = ((Delta_Dent.WebService.WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Delta_Dent.WebService.HelloWorldResponse> Delta_Dent.WebService.WebServiceSoap.HelloWorldAsync(Delta_Dent.WebService.HelloWorldRequest request)
        {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Delta_Dent.WebService.HelloWorldResponse> HelloWorldAsync()
        {
            Delta_Dent.WebService.HelloWorldRequest inValue = new Delta_Dent.WebService.HelloWorldRequest();
            inValue.Body = new Delta_Dent.WebService.HelloWorldRequestBody();
            return ((Delta_Dent.WebService.WebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Delta_Dent.WebService.Sumofnumbers1 Delta_Dent.WebService.WebServiceSoap.Sum(Delta_Dent.WebService.Sumofnumbers request)
        {
            return base.Channel.Sum(request);
        }
        
        public int Sum(int x, int y)
        {
            Delta_Dent.WebService.Sumofnumbers inValue = new Delta_Dent.WebService.Sumofnumbers();
            inValue.x = x;
            inValue.y = y;
            Delta_Dent.WebService.Sumofnumbers1 retVal = ((Delta_Dent.WebService.WebServiceSoap)(this)).Sum(inValue);
            return retVal.SumofnumbersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Delta_Dent.WebService.Sumofnumbers1> Delta_Dent.WebService.WebServiceSoap.SumAsync(Delta_Dent.WebService.Sumofnumbers request)
        {
            return base.Channel.SumAsync(request);
        }
        
        public System.Threading.Tasks.Task<Delta_Dent.WebService.Sumofnumbers1> SumAsync(int x, int y)
        {
            Delta_Dent.WebService.Sumofnumbers inValue = new Delta_Dent.WebService.Sumofnumbers();
            inValue.x = x;
            inValue.y = y;
            return ((Delta_Dent.WebService.WebServiceSoap)(this)).SumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Delta_Dent.WebService.SavePatientResponse Delta_Dent.WebService.WebServiceSoap.SavePatient(Delta_Dent.WebService.SavePatientRequest request)
        {
            return base.Channel.SavePatient(request);
        }
        
        public int SavePatient(string firstName, string surname, string genderString, string telephone, string cf, string cAsl, System.DateTime birthDate, string birthPlace, string birthProvince, bool foreigner, string billable, bool completed, bool documented, int doctorId, bool locked)
        {
            Delta_Dent.WebService.SavePatientRequest inValue = new Delta_Dent.WebService.SavePatientRequest();
            inValue.Body = new Delta_Dent.WebService.SavePatientRequestBody();
            inValue.Body.firstName = firstName;
            inValue.Body.surname = surname;
            inValue.Body.genderString = genderString;
            inValue.Body.telephone = telephone;
            inValue.Body.cf = cf;
            inValue.Body.cAsl = cAsl;
            inValue.Body.birthDate = birthDate;
            inValue.Body.birthPlace = birthPlace;
            inValue.Body.birthProvince = birthProvince;
            inValue.Body.foreigner = foreigner;
            inValue.Body.billable = billable;
            inValue.Body.completed = completed;
            inValue.Body.documented = documented;
            inValue.Body.doctorId = doctorId;
            inValue.Body.locked = locked;
            Delta_Dent.WebService.SavePatientResponse retVal = ((Delta_Dent.WebService.WebServiceSoap)(this)).SavePatient(inValue);
            return retVal.Body.SavePatientResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Delta_Dent.WebService.SavePatientResponse> Delta_Dent.WebService.WebServiceSoap.SavePatientAsync(Delta_Dent.WebService.SavePatientRequest request)
        {
            return base.Channel.SavePatientAsync(request);
        }
        
        public System.Threading.Tasks.Task<Delta_Dent.WebService.SavePatientResponse> SavePatientAsync(string firstName, string surname, string genderString, string telephone, string cf, string cAsl, System.DateTime birthDate, string birthPlace, string birthProvince, bool foreigner, string billable, bool completed, bool documented, int doctorId, bool locked)
        {
            Delta_Dent.WebService.SavePatientRequest inValue = new Delta_Dent.WebService.SavePatientRequest();
            inValue.Body = new Delta_Dent.WebService.SavePatientRequestBody();
            inValue.Body.firstName = firstName;
            inValue.Body.surname = surname;
            inValue.Body.genderString = genderString;
            inValue.Body.telephone = telephone;
            inValue.Body.cf = cf;
            inValue.Body.cAsl = cAsl;
            inValue.Body.birthDate = birthDate;
            inValue.Body.birthPlace = birthPlace;
            inValue.Body.birthProvince = birthProvince;
            inValue.Body.foreigner = foreigner;
            inValue.Body.billable = billable;
            inValue.Body.completed = completed;
            inValue.Body.documented = documented;
            inValue.Body.doctorId = doctorId;
            inValue.Body.locked = locked;
            return ((Delta_Dent.WebService.WebServiceSoap)(this)).SavePatientAsync(inValue);
        }
        
        public void SavePatientTest()
        {
            base.Channel.SavePatientTest();
        }
        
        public System.Threading.Tasks.Task SavePatientTestAsync()
        {
            return base.Channel.SavePatientTestAsync();
        }
    }
}
